'use client';

import { useEffect } from 'react';
import type { Workbox } from 'workbox-window';

/**
 * Registers the Workbox service worker (generated by scripts/build-sw.mjs)
 * in production builds so the merchant dashboard renders offline from the
 * precached app shell after the first visit.
 *
 * Skipped in development — Next.js HMR and a precaching service worker fight
 * each other — and in browsers without service worker support.
 */
export function ServiceWorkerRegistration() {
  useEffect(() => {
    if (process.env.NODE_ENV !== 'production') return;
    if (typeof window === 'undefined' || !('serviceWorker' in navigator)) return;

    let disposed = false;
    let wb: Workbox | null = null;

    // Dynamic import keeps workbox-window out of the initial bundle.
    void import('workbox-window').then(({ Workbox: WorkboxClass }) => {
      if (disposed) return;
      wb = new WorkboxClass('/sw.js');
      // Take over as soon as the updated worker finishes installing so the new
      // precache manifest is active on the next reload.
      wb.addEventListener('waiting', () => wb?.messageSkipWaiting());
      void wb.register();
    });

    return () => {
      disposed = true;
      wb = null;
    };
  }, []);

  return null;
}
